[features]
seeds = false
skip-lint = false
[programs.localnet]
spling = "9XXBUPPp5gpsd8ii6NutuyPVQMGJhFSTqcnJawgQenpt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/Users/nielsoskam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
